apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: borrow-service-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      monitor: borrow-service
  endpoints:
  - port: api
    path: '/actuator/prometheus'
    interval: 30s
    honorLabels: true