apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrow-service-deployment
  labels:
    app: borrow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borrow-service
  template:
    metadata:
      labels:
        app: borrow-service
    spec:
      containers:
        - name: borrow-service
          image: ecco18/borrow-service:v10
          env:
            - name: DATABASE_USERNAME
              value: "database_username"
            - name: DATABASE_PASSWORD
              value: "database_password"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    monitor: borrow-service
  name: borrow-app-service
spec:
  selector:
    app: borrow-service
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: borrow-service-service
spec:
  type: NodePort
  selector:
    app: borrow-service
  ports:
    - protocol: TCP
      nodePort: 30080
      port: 8080